_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.14
            "5": 0.18.0
            "8":
                - 5
                - 9
            "12": 0.18.0
            "13": linux-x86_64
batch_size:
    value: 128
dataset:
    value: input.csv
dropout rate:
    value: 0.2
finetune time:
    value: 1
finetunemodel:
    value: mlp4
head_lr:
    value: 0.001
learning_rate:
    value: 0
model_details:
    value: mlp4
seed:
    value: 495355
